# Generated by Django 5.1.4 on 2025-01-27 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="image",
            field=models.ImageField(
                blank=True,
                default="profilepic.jpg",
                null=True,
                upload_to="profile_pictures",
            ),
        ),
    ]
