# Generated by Django 5.1.4 on 2025-01-23 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("food", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="item_image",
            field=models.CharField(
                default="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTDnwVBHuYZsSc8j7YV82PckH30Tp4NaCRN1Q&s",
                max_length=500,
            ),
        ),
    ]
